---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: full-access-deploy-and-pods
subjects:
- kind: User
  name: deploy_edit
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: full-access
  apiGroup: rbac.authorization.k8s.io
  
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: full-access
  namespace: default
rules:
- apiGroups:
  - "apps"
  - ""
  resources: ["deployments", "pods"]
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete