---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-namespace-admin

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: full-access-prod
subjects:
- kind: ServiceAccount
  name: sa-namespace-admin
roleRef:
  kind: Role
  name: full-right
  apiGroup: rbac.authorization.k8s.io
  
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: full-right
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
 